from dataclasses import dataclass
from typing import Optional, Dict

@dataclass
class Scenario:
    id: str               # e.g., "SC1"
    name: str             # short name
    description: str
    expected_sources: Dict[str, bool]  # which telemetry is expected
    payload_ttps: list[dict] = None
    c2_ttps: list[dict] = None

SCENARIOS = {
    "sc1": Scenario(
        id = "SC1",
        name="Stegano",
        description="Malicious code hides inside a typosquatting package and an infected image to stealthily exfiltrate system data.",
        expected_sources={
            "azure_conn": True,
            "azure_process": True,
            "azure_security": True,
            "azure_events": True,
            "azure_port": True,
            "auditd": False,
            "auth": False,
            "suricata": False,
            "syslog": False,
            # all the logs generated by Zeek are expected
            "zeek": False,
            "tracee": False,
        },
        payload_ttps=[],
        c2_ttps=[],  
    ),
    "sc2": Scenario(
        id = "SC2",
        name="Starter",
        description="A typosquatting package abuses Windows startup and file replacement to persist and exfiltrate data via a Discord webhook.",
        expected_sources={
            "azure_conn": False,
            "azure_process": False,
            "azure_security": False,
            "azure_events": True,
            "azure_port": False,
            "auditd": False,
            "auth": False,
            "suricata": False,
            "syslog": True,
            # all the logs generated by Zeek are expected
            "zeek": False,
            "tracee": False,
        },
        payload_ttps=[],
        c2_ttps=[],  
    ),
    "sc3": Scenario(
        id = "SC3",
        name="Parallel",
        description="A malicious NPM package chain executes parallel scripts to collect and compress system/sensitive data for exfiltration.",
        expected_sources={
            "azure_conn": False,
            "azure_process": False,
            "azure_security": False,
            "azure_events": False,
            "azure_port": False,
            "auditd": True,
            "auth": True,
            "suricata": True,
            "syslog": True,
            # all the logs generated by Zeek are expected
            "zeek": True,
            "tracee": False,
        },
        payload_ttps=[],
        c2_ttps=[],  
    ),
    "sc4": Scenario(
        id = "SC4",
        name="NPMEX",
        description="Two coordinated NPM dependencies sequentially fetch and run remote payloads to steal sensitive information.",
        expected_sources={
            "azure_conn": False,
            "azure_process": False,
            "azure_security": False,
            "azure_events": False,
            "azure_port": False,
            "auditd": True,
            "auth": True,
            "suricata": True,
            "syslog": True,
            # all the logs generated by Zeek are expected
            "zeek": True,
            "tracee": False,
        },
        payload_ttps=[],
        c2_ttps=[],  
    ),
    "sc5": Scenario(
        id = "SC5",
        name="3CX",
        description="Trojanized installation software deploys multi-stage malware to steal browser data using obfuscation and DLL side-loading.",
        expected_sources={
            "azure_conn": False,
            "azure_process": False,
            "azure_security": False,
            "azure_events": True,
            "azure_port": False,
            "auditd": False,
            "auth": False,
            "suricata": False,
            "syslog": False,
            # all the logs generated by Zeek are expected
            "zeek": False,
            "tracee": False,
        },
        payload_ttps=[],
        c2_ttps=[],  
    ),
    "sc6": Scenario(
        id = "SC6",
        name="CloudEX",
        description="Attackers exploit exposed CI/CD cloud credentials to modify artifacts and insert multi-stage data-stealing malware.",
        expected_sources={
            "azure_conn": False,
            "azure_process": False,
            "azure_security": False,
            "azure_events": True,
            "azure_port": False,
            "auditd": False,
            "auth": False,
            "suricata": False,
            "syslog": True,
            # all the logs generated by Zeek are expected
            "zeek": False,
            "tracee": False,
        },
        payload_ttps=[],
        c2_ttps=[],  

    ),
    "sc7": Scenario(
        id = "SC7",
        name="LayerInj",
        description="A condition-triggered malicious function inside a Docker environment downloads fileless payloads to steal data.",
        expected_sources={
            "azure_conn": False,
            "azure_process": False,
            "azure_security": False,
            "azure_events": False,
            "azure_port": False,
            "auditd": True,
            "auth": False,
            "suricata": True,
            "syslog": True,
            # all the logs generated by Zeek are expected
            "zeek": True,
            "tracee": True,
        },
        payload_ttps=[],
        c2_ttps=[],  
    ),
}